/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_N_ffmpeg_ForJNI */

#ifndef _Included_com_N_ffmpeg_ForJNI
#define _Included_com_N_ffmpeg_ForJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_N_ffmpeg_ForJNI
 * Method:    open
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_capston_L_Player_ForJNI_open
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_N_ffmpeg_ForJNI
 * Method:    Init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_capston_L_Player_ForJNI_Init
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
